_wandb:
    value:
        cli_version: 0.22.2
        e:
            vu7nguuli6fczh48xeaypawzpsxz1624:
                codePath: gepa_github.ipynb
                codePathLocal: gepa_github.ipynb
                cpu_count: 12
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1002710233088"
                        used: "371524534272"
                email: jon.eba08@gmail.com
                executable: c:\Users\Gamer\Downloads\Python\ALFA UROP\.venv\Scripts\python.exe
                git:
                    commit: ac334f1bc3f6b9bbafdf23bfb951e309cdfb7bae
                    remote: https://github.com/JonE01/ALFA-UROP.git
                host: BOOK-8ISKP3RTT5
                memory:
                    total: "16718426112"
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\Gamer\Downloads\Python\ALFA UROP\gepa_github.ipynb
                python: CPython 3.12.1
                root: c:\Users\Gamer\Downloads\Python\ALFA UROP
                startedAt: "2025-10-29T00:36:14.110315Z"
                writerId: vu7nguuli6fczh48xeaypawzpsxz1624
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 75
                - 95
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 75
                - 95
                - 105
            "3":
                - 2
                - 61
            "4": 3.12.1
            "5": 0.22.2
            "6": 4.57.1
            "8":
                - 1
                - 3
            "12": 0.22.2
            "13": windows-amd64
